name: Publish to PyPi

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[test]
          pip install wheel twine
      - name: Run tests with pytest
        run: ./run_tests.sh
      - name: Build
        run: python setup.py bdist_wheel
      - name: Release
        env:
          PYPI_USER: ${{ env1.PYPI_USER }}
          PYPI_PASSWORD: ${{ env1.PYPI_PASSWORD }}
        run: |
          echo $PYPI_USER
          twine upload --username "$PYPI_USER" --password "$PYPI_PASSWORD" dist/*